### ISSUE TITLE
Question about Dense Landmark Indices in Metrical-Tracker with BFM Model

### ISSUE THREAD

**Issue by BoyiZhao** [Zielon/metrical-tracker#23]
I'm currently working on adapting the Metrical-Tracker for use with the BFM (3D Morphable Face Model) and have a question regarding the process of obtaining dense landmark indices. In the tracker.py file, I noticed the use of the mediapipe_landmark_embedding.npz file to get indices for landmarks corresponding to the FLAME model.

Specifically, I'm trying to understand the steps involved in using MediaPipe to determine indices for dense landmarks in FLAME when integrating the tracker with the BFM model. During optimization, I'm facing difficulties in obtaining the vertex indices for lmkMP (dense landmarks) in the BFM mesh.

**Comment by Zielon** [comment]
In order to obtain the embedding/correspondence you could try the steps:

1) Render synthetic BFM average face from a set of predefined views.
2) For each rendered view you can store rasterized face id, barycentric coordinates, etc, all of that per pixel. Those are additional render targets. Easily obtained from pytroch3D.
3) Once you know per pixel face id and bary coords, you run the MediaPipe landmarks detection on the synthetic rendered image.
4) For each landmark now you know the face id, etc. From that and bary coords you can exactly calculate the landmark on BFM face model.

You can average the predictions over the predefined views to get more robust landmarks.
