### ISSUE TITLE
About Key Frame Selection and Identity Selection

### ISSUE THREAD

**Issue by DongzeLi-CASIA** [Zielon/metrical-tracker#29]
Hi, thank you for your amazing work!
I have some questions, described concretely below.
- Key frame selection: What is the importance of choosing a neutral face? Does the face have to keep **both the pose and expression neutral** or **just the pose** (mentioned in readme.md)? What if a choose a frame with a large expression variation or pose variation e.g. laughing, as the key frame? Does it affects the accuracy of the extrinsic estimation or something else?
- Is it important to choose a neutral face for extracting `identity.npy` with MICA ? 

Thanks in advance, looking forward to your reply !

**Comment by Tiandishihua** [comment]
> Hi, thank you for your amazing work! I have some questions, described concretely below.
> 
> * Key frame selection: What is the importance of choosing a neutral face? Does the face have to keep **both the pose and expression neutral** or **just the pose** (mentioned in readme.md)? What if a choose a frame with a large expression variation or pose variation e.g. laughing, as the key frame? Does it affects the accuracy of the extrinsic estimation or something else?
> * Is it important to choose a neutral face for extracting `identity.npy` with MICA ?
> 
> Thanks in advance, looking forward to your reply !

Have you solved this problem?

**Comment by Zielon** [comment]
Hey, keyframe is important for a good initialization of texture (appearance model), camera intrincics, optionally improving MICA prediction and predicting global rotation and translation. Since it is an iterative optimizer you need good starting point in order to avoid many optimization iteration which in this case usually is fixed. So, the best would be a keyframe where an actor is in neutral pose and expressions.

Anything else will give bad initialization which ultimately results that optimizer get stuck in some suboptimal local minimum.
